SKIRT/SKIRT9

- SKIRT/core/NestedLogWavelengthGrid.cpp
The `NestedLogWavelengthGrid` didn't allow (one of) the limits of the inner grid to be the same as the corresponding limit of the outer grid. This is now fixed.
> Allow nested wavelength grid to touch the base grid

- SKIRT/core/DustEmissionWavelengthGridProbe.cpp
- SKIRT/core/DustEmissionWavelengthGridProbe.hpp
- SKIRT/core/DustEmissivityProbe.cpp
- SKIRT/core/DustEmissivityProbe.hpp
- SKIRT/core/RadiationFieldWavelengthGridProbe.cpp
- SKIRT/core/RadiationFieldWavelengthGridProbe.hpp
- SKIRT/core/SimulationItemRegistry.cpp
Add probes that output the radiation field wavelength grid or the dust emission wavelength grid.
**Motivation**
The detailed of these wavelength grids are often useful when studying convergence (i.e. minimizing the number of wavelength bins) for a given input model. Even if these wavelength grids can be obtained as part of other probes, the extra info is in this case not needed (and it takes time to generate).
> add probes for RF and emission WLG

- SKIRT/core/PlanarMediaDensityCutsProbe.cpp
- SKIRT/core/PlanarMediaDensityCutsProbe.hpp
- SKIRT/core/SimulationItemRegistry.cpp
New Planar media density cuts probe (see #12).
Main changes are to centering of perpendicular axes, where rather than being set automatically to zero are centred on the grid coordinate centre (`xcenter,ycenter,zcenter`).
double z = zd ? (zbase + j*zpsize) : zcenter;
...
double x = xd ? (xbase + i*xpsize) : xcenter;
double y = yd ? (ybase + (zd ? i : j)*ypsize) : ycenter;
**Motivation**
#12
**Tests**
Added to .ski as 
<PlanarMediaDensityCutsProbe probeName="planar_dns"/>
returns .fits as expected.
> added planar media density cuts probe

- SKIRT/core/AbstractPlanarCutsProbe.hpp
- SKIRT/core/DefaultDustTemperatureCutsProbe.cpp
- SKIRT/core/DefaultDustTemperatureCutsProbe.hpp
- SKIRT/core/DefaultMediaDensityCutsProbe.cpp
- SKIRT/core/DefaultMediaDensityCutsProbe.hpp
- SKIRT/core/DefaultRadiationFieldCutsProbe.cpp
- SKIRT/core/PlanarDustTemperatureCutsProbe.cpp
- SKIRT/core/PlanarDustTemperatureCutsProbe.hpp
- SKIRT/core/PlanarMediaDensityCutsProbe.cpp
- SKIRT/core/PlanarMediaDensityCutsProbe.hpp
- SKIRT/core/PlanarRadiationFieldCutsProbe.cpp
- SKIRT/core/PlanarRadiationFieldCutsProbe.hpp
- SKIRT/core/SimulationItemRegistry.cpp
Add probes for planar medium density, dust temperature, and radiation field at an arbitrary position in the spatial domain (but still parallel to the coordinate planes). Refactored the corresponding default cut probes to use the same code (without changing their behaviour).
**Important note**
This is an extension of the earlier contribution by @christopherlovell discussed in issue #12 . However, note that the default value for the cut position now changed to (0,0,0) instead of the center of the spatial grid. To get the same behaviour, users must explicitly specify the coordinates of the grid center.
**Motivation**
Allow users to probe these quantities at other locations in the model than along the coordinate planes. 
**Tests**
New functional tests were added to the …
> Add probes for planar cuts at arbitrary positions in the model

- SKIRT/core/VoronoiMeshSnapshot.cpp
- SKIRT/mpi/ProcessManager.cpp
- SKIRT/mpi/ProcessManager.hpp
Implement functions to communicate the results of Voronoi grid construction between MPI processes, so that Voronoi grids are now being built using full hybrid parallellization (parallel threads **and** parallel processes).
**Motivation**
See issue #4.
**Tests**
All functional tests still work. Tested parallel execution on two models with up to 2 million cells.
>  Support MPI for Voronoi grid calculation

- SKIRT/core/RadialVectorField.hpp
Fix metadata causing CylindricalVectorField to appear twice in the list of classes on the Web site.
**Context**
Issue reported by @mstalevski.
> Fix metadata causing CylindricalVectorField to appear twice

- SKIRT/core/MultiGrainDustMix.cpp
Fix a bug that caused NaN values for the mean mass of a dust population's size bin if the size bin does not contain any dust. The code depending on the mean mass happened to behave as if the NaN value was actually zero, so that the end result was correct anyway.
**Motivation**
Intermediate NaN values are evil. A future update to the code using the mean mass might have unsurfaced a very hard to find bug.
**Context**
Thanks to @drvdputt for reporting this (internal) bug.
> Avoid NaNs in (unused) precalculated data

- SKIRT/core/MonteCarloSimulation.cpp
- SKIRT/core/SecondarySourceSystem.cpp
- SKIRT/utils/StokesVector.hpp
Two changes:
- polarisation effects are now properly taken into account when launching emission peel off photon packets
- emission now emits polarised photon packets if spheroidal dust particles are present
**Motivation**
This pull request adds the functionality required to model polarised dust emission by spheroidal dust grains.
**Tests**
[spheroid_test.zip](https://github.com/SKIRT/SKIRT9/files/4160103/spheroid_test.zip)
The above file contains a `.ski` file and a `.stab` emission coefficient data file for a single cell SKIRT simulation that uses the proposed polarised dust emission mechanism (launching and peel off; interaction of the emitted photons with the medium is not tested yet). The results can be tested against the expected emission and agree quite well:
There …
> Polarised dust emission

- SKIRT/core/Sphere1DSpatialGrid.cpp
- SKIRT/core/Sphere1DSpatialGrid.hpp
Sphere1DSpatialGrid gets an extra property 'minRadius', analogous to 'maxRadius' of the parent class SphereSpatialGrid.
**Motivation**
This is useful for running thin spherical shell models, for which the inner cavity is relatively large. It avoid having to introduce a large number of empty shells, and makes it more intuitive to match the grid boundary with the medium boundary.
**Tests**
I have attached two .ski files which should be equivalent. Unfortunately, the results are not exactly the same, since the photons are moved to the first cell when they are in the central cavity. But they should be statistically the same, if this was implemented correctly.
[shell_test.zip](https://github.com/SKIRT/SKIRT9/files/4225439/shell_test.zip)
**Context**
This has been implemented in …
> minRadius feature for Sphere1DSpatialGrid

- SKIRT/core/TabulatedDustMix.cpp
- SKIRT/core/TabulatedDustMix.hpp
- SKIRT/utils/NR.hpp
The tabulated dust mixes (List and File) now properly clamp values outside of the tabulated wavelength range to the values at the outer borders.
**Motivation**
There was an inconsistency between the documented and actual behavior.
**Tests**
All function tests run after the intended changes are accounted for.
> clamp values in tabulated dust mix

- SKIRT/core/AllSkyInstrument.cpp
- SKIRT/core/FluxRecorder.cpp
- SKIRT/core/FluxRecorder.hpp
- SKIRT/core/FrameInstrument.cpp
- SKIRT/core/PerspectiveInstrument.cpp
The parallel instruments (FrameInstrument, FullInstrument) now output the extent of the spatial axes in FITS data cubes in angular units corresponding to the distance or redshift from the instrument to the simulated model, as opposed to using rest-frame model distances. The values of the surface brightness pixels in the data cubes do NOT change.
**Motivation**
These new units make a lot more sense observationally, especially when considering models at nonzero redshift.
**Tests**
All functional tests still produced the same results, modulo the intended change.
**Context**
The other instruments (e.g. AllSkyInstrument and PerspectiveInstrument) and all probes are considered to operate in the model rest frame and therefore still output rest-frame model distances for the …
> Parallel instruments output the extent of the spatial axes in angular units 

- SKIRT/core/SkirtUnitDef.cpp
Fixed the default value of the number surface density unit in the StellarUnit system.
**Motivation**
Q&A crashed when entering normalization on number surface density when using stellar units.
**Tests**
Added new test case. Other tests cases still run.
**Context**
Error report by Bert Vander Meulen.
> Fix default number surface density for stellar units

- SKIRT/core/InstrumentSystem.cpp
This change fixes a bug in the optimization of consecutive instruments with the same line of sight. In some cases, an instrument would incorrectly use the line of sight of the previous instrument instead of its own line of sight.
**Motivation**
The previous behavior was incorrect.
**Tests**
All functional tests still run and a new test has been added for this particular problem.
**Context**
Thank you to @anatrcka for reporting this problem.
> Fix bug in optimization of instruments with the same line of sight

- SKIRT/core/FilePaths.cpp
- SKIRT/core/FilePaths.hpp
- SKIRT/main/SkirtCommandLineHandler.cpp
SKIRT now logs a warning message both on the console and in each simulation's log file when one of the following issues arise:
- the Core resource pack is not installed;
- the version number of any installed resource pack does not match the expected version.
**Motivation**
We will shortly be releasing a new version of the Core resource pack with a small change that is hard to detect without verifying the version number. It is therefore important to notify users if they have the incorrect version installed.
**Tests**
All functional tests still run.
> Warning message for incorrect installed resource pack version

- SKIRT/resources/ExpectedResources.txt
Increase the expected version of the Core resource pack from 2 to 3. The updated resource pack must be downloaded separately by running `./downloadResources.sh` from the `~SKIRT/git' directory. It contains a version of the Mappings SED family templates from which the three overly prominent Carbon emission lines have been removed from the dust continuum.
**Motivation**
The problem is that these emission lines are defined in the templates through just a single point in a coarse wavelength grid. As a result they are much wider than they should be and thus they carry much more energy than physically justified. The plot below shows the original templates in reddish color and the adjusted templates (overplotted) in blueish color. The dots show convolved fluxes for the Herschel …
> Remove the carbon emission lines from the Mappings dust continuum

- SKIRT/core/AllSkyInstrument.hpp
- SKIRT/core/HEALPixSkyInstrument.cpp
- SKIRT/core/HEALPixSkyInstrument.hpp
This pull request fixes the calibration of the fluxes within the HEALPixSkyInstrument.
**Motivation**
The flux calibration for the HEALPixSkyInstrument (and the AllSkyInstrument as well) is ill defined, since the pixels of the instrument only have an angular size, and no associated physical size. As a result, it is impossible to determine what the angular size of a pixel is as seen from a distant object. This size is however required to properly normalise the flux coming from that object.
The solution (as also used by the AllSkyInstrument) is to assume a physical radius for the instrument. This radius can be used to convert angular sizes into physical sizes, fixing the angular size of the pixels for all objects. The choice of radius is in principle arbitrary, but should …
> HEALPixSkyInstrument flux calibration

- SKIRT/main/SkirtCommandLineHandler.cpp
Avoid duplicate info messages at the start of the simulation when running with multiple processes.
**Motivation**
This (minor) issue was introduced with the previous commit (repeat warnings and errors at the end of the simulation).
> Avoid duplicate info messages in multi-process mode

- SKIRT/core/SecondarySourceSystem.cpp
Turns out the sampling of random photon packet directions for polarised secondary emission was wrong: the directions were not sampled correctly. There were two issues: first of all, there was a small issue with the calculation of the cumulative distribution function for the sampling. Second and most important, in the old implementation the randomly generated direction was not transformed from the dust frame (reference frame with the z-axis along the magnetic field direction) to the lab frame, leading to a completely incorrect sampling of the anisotropic emission profile.
**Motivation**
This issue was discovered while running a dedicated test case for secondary emission, described in detail below.
**Tests**
To test the intensity and polarisation state of secondary emission …
> Correctly sample the anisotropic polarised emission profile

- SKIRT/core/CellGeometry.cpp
- SKIRT/core/CellGeometry.hpp
- SKIRT/core/CellMedium.cpp
- SKIRT/core/CellMedium.hpp
- SKIRT/core/CellSnapshot.cpp
- SKIRT/core/CellSnapshot.hpp
- SKIRT/core/CellSource.cpp
- SKIRT/core/CellSource.hpp
- SKIRT/core/SimulationItemRegistry.cpp
- SKIRT/core/Snapshot.cpp
- SKIRT/core/Snapshot.hpp
This pull request adds the the capability to import snapshot data (for media and sources) from a list of cuboidal cells.
Each line in the input text file represents a cuboidal cell lined up with the coordinate axes, specifying the coordinates of the lower-left and upper-right corners of the cell along with any relevant cell properties. The intention is for the cells to define a partition of the spatial domain, however this is not enforced. When two or more cells overlap at a given position, the properties for that position will be taken from the cell that is listed first in the imported file. When no cells overlap a given    position, the density at that position is considered to be zero. **To avoid thin slices of zero density between cells, the coordinates for common …
> Add snapshot import from list of cuboidal cells (as simpler alternative for AMR)

- SKIRT/utils/LockFree.hpp
This pull-request fixes the incorrect results produced by SKIRT when compiled with recent versions of Microsoft Visual Studio. Specifically, it adjusts the `LockFree::add()` function so that it conforms both to C++14 and C++20 conventions.
**Technicalities**
The `LockFree::add()` function needs a compile-time construct to transform the target `double` (passed as a reference) to an `atomic<double>` used for the atomic add operation _without producing any machine instructions_. The previous code used a _placement_ `new` for this purpose, which allocates the `atomic<double>` variable at the regular `double`'s location. The new code uses an `interpret_cast<>` instead.
**Motivation**
The C++14 specification says that a placement `new` does not initialize the newly allocated …
> Fix Lockfree::add for Microsoft Visual Studio compiler

- SKIRT/core/ReadFits3DGeometry.cpp
- SKIRT/core/ReadFits3DGeometry.hpp
- SKIRT/core/ReadFitsGeometry.hpp
- SKIRT/core/SimulationItemRegistry.cpp
Added the functionality to read the spatial luminosity distribution for sources or the spatial density distribution for the medium from a .fits datacube.
**Motivation**
This allows SKIRT users to introduce arbitrary, asymmetric geometries into the simulation. 
**Tests**
This class has been thoroughly tested using a simple cubic geometry (cube.fits used by cube.ski). To exhibit the possibilities a top-toy was imported into SKIRT (top.fits used by top.ski). Test files are available here: [ReadFits3DGeometry_TestFiles.zip](https://github.com/SKIRT/SKIRT9/files/5495571/ReadFits3DGeometry_TestFiles.zip)
**Guidelines**
The model geometry is set by two parameters: the input filename and the pixelscale (i.e. the physical length per pixel).
**Context**
The example cube.fits …
> Added a 3D geometry read from a .fits datacube

- SKIRT/core/LyaUtils.cpp
This pull request fixes the slight but systematic asymmetry noted in Lyman-alpha SEDs for static sphere benchmarks. The culprit was a bug in the implementation of the choice between isotropic and dipole scattering phase functions (the dipole was selected only for wavelengths on one side of the Lyman-alpha line center).
Also, a minor performance optimization was made in the calculation of the wavelength shift for each scattering event.
**Tests**
All functional tests and benchmark results have been verified for this update.
**Context**
All 1D Lyman-alpha benchmarks now seem to run with satisfactory results.
> Fix the asymmetry in Lyman-alpha SEDs for static spheres

- SKIRT/core/AdaptiveMeshSnapshot.cpp
- SKIRT/core/CartesianSpatialGrid.cpp
- SKIRT/core/Cylinder2DSpatialGrid.cpp
- SKIRT/core/Sphere1DSpatialGrid.cpp
- SKIRT/core/Sphere2DSpatialGrid.cpp
- SKIRT/core/TreeSpatialGrid.cpp
- SKIRT/core/VoronoiMeshSnapshot.cpp
This change suppresses a compiler warning issued by recent GCC version for `switch` statements that include a fall-through `case`. The new path segment calculators include such a construct. The warning is suppressed by adding a specific comment that gets captured by the compiler.
**Motivation**
Compiler warnings are confusing.
**Tests**
There are no changes to the code itself.
> Avoid compiler warning from GCC

- downloadResources.sh
The `downloadResources.sh` script did not check that `unzip` is available before downloading the resources, which would lead to an unnecessary download of 650MB. I added an additional check before the download starts to make sure the downloaded archives can be unzipped.
**Context**
When installing SKIRT within a Docker container, the base image might not have `unzip` available. Installing `unzip` takes a few seconds, but if you only notice it is missing after the download completed, this leads to a lot of unnecessary network traffic.
> Check that unzip is available in downloadResources

- SKIRT/core/AllSkyInstrument.cpp
- SKIRT/core/AllSkyInstrument.hpp
- SKIRT/core/AllSkyProjection.cpp
- SKIRT/core/AllSkyProjection.hpp
- SKIRT/core/DistantInstrument.cpp
- SKIRT/core/DistantInstrument.hpp
- SKIRT/core/FluxRecorder.cpp
- SKIRT/core/FluxRecorder.hpp
- SKIRT/core/FrameInstrument.cpp
- SKIRT/core/FullInstrument.cpp
- SKIRT/core/HEALPixSkyInstrument.cpp
- SKIRT/core/HEALPixSkyInstrument.hpp
- SKIRT/core/Instrument.hpp
- SKIRT/core/OpticalDepthMapProbe.cpp
- SKIRT/core/PerspectiveInstrument.cpp
- SKIRT/core/PerspectiveInstrument.hpp
- SKIRT/core/SEDInstrument.cpp
This update fixes the surface brightness calibration and some coordinate transform issues for local instruments, including the `AllSkyInstrument`, the `HEALPixSkyInstrument`, and the `PerspectiveInstrument`. Distant instruments, including the `SEDInstrument`, the `FrameInstrument`, and the `FullInstrument`, are not affected.
For all instruments, the contribution of a given source to the flux detected in a particular pixel depends on the source's distance and on the solid angle subtended by the pixel. Because distant instruments assume that all sources in the model are at the same (large) distance from the instrument, this "calibration" can occur at the end of the simulation after all photon packet contributions have been accumulated. For local instruments, however, the …
> Fix surface brightness calibration and coordinate transforms for local instruments

- SKIRT/core/FrameInstrument.cpp
- SKIRT/core/FrameInstrument.hpp
- SKIRT/core/SEDInstrument.cpp
- SKIRT/core/SEDInstrument.hpp
This update adds an optional circular aperture to the SED instrument. 
Specifically, the `SEDInstrument` now allows configuring the radius of a circular aperture centered on the origin of the model coordinate system and in the plane perpendicular to the instrument's line of sight. Photon packets arriving from a point that parallel projects outside of this aperture are ignored. If the configured radius is zero (the default value), the instrument does not have an aperture, or, equivalently, the aperture radius is infinite.
**Motivation**
Similar functionality could be obtained by configuring a frame instrument and then (e.g. in Python) integrating the surface brightness over the pixels inside the circular aperture. However, this requires more memory during the simulation as …
> Add circular aperture to SED instrument

- SKIRT/core/FluxRecorder.cpp
This pull request fixes a sometimes crashing bug in the `FluxRecorder` code that records statistics for surface brightness data cubes (or frames, for a single wavelength). The bug was reported as issue #91.
**Effects of the bug on results before this fix**
In summary, the effect on results is limited to a single corner pixel in the statistics frames produced by SKIRT.
The bug occurred only with enabled `recordStatistics` property for a `FrameInstrument` or `FullInstrument`. The surface brightness results were not affected. However, any contributions to the statistics by photon packets arriving outside of the field of view, rather than being discarded, were accumulated in one of the corner pixels in the frame for the _previous_ wavelength bin. For contributions in the first …
> Fix out-of-range write in surface brightness statistics

- SKIRT/core/AdaptiveMeshMedium.cpp
- SKIRT/core/Configuration.cpp
- SKIRT/core/Configuration.hpp
- SKIRT/core/MeshMedium.hpp
- SKIRT/core/Snapshot.hpp
- SKIRT/core/VoronoiMeshMedium.cpp
- SKIRT/core/VoronoiMeshMedium.hpp
- SKIRT/core/VoronoiMeshSnapshot.cpp
- SKIRT/core/VoronoiMeshSnapshot.hpp
This update offers the possibility to forego the construction of the Voronoi tessellation for imported VoronoiMesh media in case the full tessellation is not needed for purposes other than sampling the density distribution. An important use case is when the medium density distribution defined on the Voronoi grid is resampled to an octree grid to perform radiative transfer. To enable this use case, the massType option can be set to include both mass density and volume-integrated mass (or both number density and volume-integrated number) in the imported data file. 
**Motivation**
The algorithm used by the VoronoiMeshSnapshot class for constructing Voronoi tessellations sometimes fails (for example, when generating sites are too close to each other). In those cases, it can be …
> Avoid construction of Voronoi tessellation for some use cases

- SKIRT/core/RadiationFieldAtPositionsProbe.cpp
- SKIRT/core/RadiationFieldAtPositionsProbe.hpp
- SKIRT/core/SimulationItemRegistry.cpp
Add a probe that outputs the mean radiation field intensity at the positions listed in a user-provided input file. This allows, for example, to probe the radiation field at the positions listed in a Particle or VoronoiMesh import file used for defining sources or media by configuring this new probe with the same import file (any columns other than the position coordinates will be ignored).
**Motivation**
As a first order approximation for handling radiation field (RF)-dependent line emission in SKIRT (for certain lines) we consider a two-step approach: (1) calculate the RF using dust only and (2) redo the simulation including line emission parametrized using info derived from the RF calculated in step 1. In order for this to work, we need to “map” the SKIRT RF output back …
> Add probe for radiation field at specified positions

- SKIRT/core/StoredColumns.cpp
- SKIRT/core/StoredColumns.hpp
- SKIRT/core/TextInFile.cpp
- SKIRT/core/TextInFile.hpp
**Motivation**
With the ever increasing resolution of hydro simulations, column text import files representing a galaxy snapshot may easily contain 100 million lines. Reading these large column text files can be very slow (on the order of one minute per ten million lines) and cannot be accelerated through parallelization. Although the time spent reading import files is usually still small compared to the total simulation time, these long setup times are especially annoying while interactively testing or fine-tuning a SKIRT configuration.
It has been suggested, among others by @cbehren and @bwvdnbro, to support a binary format such as HDF5 for SKIRT import. However, this would bring extra complexities. Firstly, we would need to introduce a dependency on the HDF5 library (which, admittedly, …
> Support binary stored columns format as a faster alternative for column text files

- SKIRT/core/FrameInstrument.hpp
- SKIRT/core/FullInstrument.hpp
Augment the documentation of the distant instruments (`SEDInstrument`, `FrameInstrument`, and `FullInstrument`) to explicitly specify the aperture used in all cases. Specifically, the `SEDInstrument` embedded in the `FullInstrument` always uses an infinite aperture radius. Therefore, when interpreting the instrument output for a particular wavelength, spatially integrating the surface brightness recorded by the embedded `FrameInstrument` might produce a lower flux density value than the one recorded by the embedded `SEDInstrument`.
**Motivation**
This (historically inspired) behavior has confused several users because it was not clearly documented.
> Add aperture info to FullInstrument documentation

- SKIRT/core/GeometricMedium.cpp
- SKIRT/core/GeometricMedium.hpp
- SKIRT/core/ImportedMedium.cpp
- SKIRT/core/ImportedMedium.hpp
- SKIRT/core/Medium.hpp
Fix support for spatially variable material mixes with imported mesh media (including Voronoi and AMR meshes). The mechanism worked with particle media but caused a crash when used with mesh media.
**Motivation**
Fix a crashing bug.
**Tests**
All existing functional tests work. New tests have been added for these use cases.
> Fix spatially variable material mix support for imported mesh media

- SKIRT/core/VoronoiMeshSpatialGrid.cpp
Fix a bug that caused SKIRT to produce NaN densities and hang indefinitely when shooting photon packets in the following special case: import a medium defined on a Voronoi mesh, use the same mesh as a radiative transfer grid, and have zero mass in all cells within the bounding box of the grid, so that the total medium mass is zero.
**Motivation**
Importing a zero-mass medium might be unusual, but it is perfectly valid.
**Tests**
Added a functional test for this special case; all existing tests still work.
> Fix issue with zero-mass imported Voronoi mesh

- SKIRT/core/Cylinder2DSpatialGrid.cpp
This update fixes the incorrect treatment of photon packets originating outside of the domain of an axially symmetric grid implemented by `Cylinder2DSpatialGrid`. In other words, in 2D SKIRT models using the `Cylinder2DSpatialGrid`, the paths for photon packets emitted from sources outside of the cylindrical grid boundaries were calculated incorrectly. For example, consider a simple model with a dusty Plummer sphere illuminated by a thin ring surrounding it in the equatorial plane. Viewing this configuration at an inclination of 85 degrees, the correct result (as can be easily verified by using, for example, a 3D Cartesian grid) would be:
The `Cylinder2DSpatialGrid`, however, when configured with a radial boundary smaller than the source ring, yielded the following …
> Fix incorrect treatment of photon packets originating outside of Cylinder 2D grid

- SKIRT/core/ProjectedMediaDensityProbe.cpp
- SKIRT/core/ProjectedMediaDensityProbe.hpp
- SKIRT/core/SimulationItemRegistry.cpp
- SKIRT/utils/Direction.hpp
`ProjectedMediaDensityProbe` outputs a projection of the grid-discretized media density in the simulation on a plane along a given line of sight. The viewing angle, field of view and pixel resolution are configured in the same way as for a `FrameInstrument` so that it is easy to obtain a mass density projection matching the position of an instrument.
**Motivation**
This capability was suggested by users a number of times, including most recently by Gayathri Eknath at Cardiff University in Wales.
**Tests**
New functional tests were added.
> Add probe to output projected surface density (dust) or column density (electrons, gas)

- SKIRT/core/DustMix.cpp
- SKIRT/core/DustMix.hpp
- SKIRT/core/ElectronMix.cpp
- SKIRT/core/ElectronMix.hpp
- SKIRT/core/FragmentDustMixDecorator.cpp
- SKIRT/core/FragmentDustMixDecorator.hpp
- SKIRT/core/ImportedSource.cpp
- SKIRT/core/LyaNeutralHydrogenGasMix.cpp
- SKIRT/core/LyaNeutralHydrogenGasMix.hpp
- SKIRT/core/MaterialMix.hpp
- SKIRT/core/MultiGrainDustMix.cpp
- SKIRT/core/NormalizedSource.cpp
- SKIRT/core/NormalizedSource.hpp
- SKIRT/core/SingleGrainDustMix.cpp
- SKIRT/core/Source.cpp
- SKIRT/core/Source.hpp
**Log messages**
With this update SKIRT issues a warning to the simulation log in the following cases:
- The wavelength range of an SED or SED family does not fully cover the wavelength range configured for the source system (so that the specific luminosity will be zero outside the supported range).
- The optical properties for a dust mix are not available for all wavelengths (potentially) used in the simulation. The values outside of the supported wavelength range are clamped to the nearest available value (except in radio range; see next section).
These extra log messages help the user discover/understand limitations that might otherwise go unnoticed. For example:
- The spectrum for the Bruzual-Charlot SED family "ends" at 160 micron. While this is not a problem for regular …
> Log a warning for insufficient wavelength ranges; force dust cross sections to zero beyond 10 cm

- SKIRT/core/ComptonPhaseFunction.cpp
- SKIRT/core/ComptonPhaseFunction.hpp
- SKIRT/core/Configuration.cpp
- SKIRT/core/ElectronMix.cpp
- SKIRT/core/ElectronMix.hpp
- SKIRT/core/LyaNeutralHydrogenGasMix.cpp
- SKIRT/core/LyaNeutralHydrogenGasMix.hpp
- SKIRT/core/MaterialMix.cpp
- SKIRT/core/MaterialMix.hpp
- SKIRT/core/RangeWavelengthDistribution.hpp
- SKIRT/core/SpinFlipHydrogenGasMix.hpp
- SKIRT/utils/PhotonPacket.cpp
- SKIRT/utils/PhotonPacket.hpp
This update introduces new physics for electron populations:
- For wavelengths shorter than 10 nm, the electron mix switches to Compton scattering. In contrast to Thomson scattering, the scattering cross section and phase function depend on wavelength, and the scattering interaction is inelastic, causing a wavelength shift. The Compton implementation does not support polarization. If support for polarization is requested, Thomson scattering is used even for short wavelengths.
- The electron mix supports optional thermal velocity dispersion based on the local temperature, which can be provided as a column in an import file or as a constant temperature value for a built-in geometry.
**Motivation**
These processes are relevant in the X-ray wavelength range.
**Tests**
Existing …
> Compton scattering and thermal velocity dispersion for electrons

- SKIRT/core/DefaultElectronTemperatureCutsProbe.cpp
- SKIRT/core/DefaultElectronTemperatureCutsProbe.hpp
- SKIRT/core/ElectronMix.cpp
- SKIRT/core/ElectronMix.hpp
- SKIRT/core/ElectronTemperaturePerCellProbe.cpp
- SKIRT/core/ElectronTemperaturePerCellProbe.hpp
- SKIRT/core/MediumSystem.cpp
- SKIRT/core/MediumSystem.hpp
- SKIRT/core/PlanarElectronTemperatureCutsProbe.cpp
- SKIRT/core/PlanarElectronTemperatureCutsProbe.hpp
- SKIRT/core/SimulationItemRegistry.cpp
This update adds probes for the electron temperature for each spatial cell or along planar cuts.
**Motivation**
These probes are relevant in conjunction with the recently added thermal velocity dispersion option for electrons.
> Add probes for electron temperature (cuts and per cell)

- SKIRT/core/DustMix.cpp
**Background and motivation**
Many of the dust models in SKIRT employ Henley-Greenstein (HG) scattering with a phase function parameterized on the asymmetry parameter g where -1 <= g <= 1. For wavelengths in the x-ray range, dust grains exhibit strong forward scattering, and several of the dust models currently built into SKIRT list g values for those wavelengths that are very close to or even equal to 1, indicating extreme or even total forward scattering.
The expression for the HG phase function becomes numerically unstable for abs(g) > 1-1e-7. Clipping g to that maximum magnitude would not alter the physics and thus would represent no problem.
More annoyingly, however, HG phase function values for some scattering angles become exceedingly large or small when abs(g) > 0.95. These values …
> Avoid artificial "noise" for extreme HG forward scattering

- SKIRT/core/DustAbsorptionPerCellProbe.cpp
- SKIRT/core/DustEmissivityProbe.cpp
- SKIRT/core/FluxRecorder.cpp
- SKIRT/core/InstrumentWavelengthGridProbe.cpp
- SKIRT/core/LaunchedPacketsProbe.cpp
- SKIRT/core/LuminosityProbe.cpp
- SKIRT/core/OpticalMaterialPropertiesProbe.cpp
- SKIRT/core/PlanarRadiationFieldCutsProbe.cpp
- SKIRT/core/RadiationFieldAtPositionsProbe.cpp
- SKIRT/core/RadiationFieldPerCellProbe.cpp
- SKIRT/core/SkirtUnitDef.cpp
- SKIRT/core/Units.cpp
- SKIRT/core/Units.hpp
- SKIRT/utils/NR.cpp
- SKIRT/utils/NR.hpp
- SMILE/fundamentals/Indices.hpp
- SMILE/schema/ItemInfo.hpp
This pull request introduces a user configuration option on the units system for selecting a wavelength output style in addition to a flux output style. This new option determines how the internal wavelength quantity is represented in output files: as a wavelength (e.g., in micron), as a frequency (e.g., in GHz), or as a photon energy (e.g., in keV).
In the output of instruments and probes, wavelength-iterated rows, columns, and data frames are always sorted in increasing order of the spectral quantity being used. For example, if the energy wavelength output style is selected, the rows of an SED output file are in increasing energy order, corresponding to decreasing wavelength order.
**Motivation**
In conjunction with the previously introduced energy units for fluxes, this …
> Introduce configuration option for wavelength output style

- SKIRT/core/ContGasSecondarySource.cpp
- SKIRT/core/DustSecondarySource.cpp
This update fixes a bug that caused a crash at the start of secondary emission of the second simulation performed consecutively in the same SKIRT run in single thread mode. This issue has gone unnoticed for a long time because SKIRT is not often used in this mode. Usually one performs just one simulation using multiple threads as opposed to multiple consecutive simulations using a single thread.
**Tests**
All functional tests still succeed. Because each functional test is performed in a separate SKIRT run, the bug considered here did not affect the functional tests.
> Fix secondary emission crash when two simulations are performed consecutively in single thread mode

- SKIRT/core/ElectronMix.cpp
- SKIRT/core/ImportedSource.cpp
- SKIRT/core/LineGasSecondarySource.cpp
- SKIRT/core/Random.cpp
- SKIRT/core/Random.hpp
- SKIRT/core/Units.cpp
- SKIRT/core/Units.hpp
This update fixes a bug in the procedure for drawing a random dispersion velocity from the Maxwell-Boltzmann velocity distribution. The resulting Doppler shift for emitted or interacting photon packets had a sharply peaked profile instead of the expected Gaussian profile.
This issue affected three areas:
- An imported primary source with the "import velocity dispersion" flag turned on.
- Secondary line emission from gas (currently used only in the non-operational spin-flip material mix).
- Thermal dispersion in electron mixes configured with a nonzero temperature (recently added and still being tested).
**Tests**
The Doppler shift profiles for primary and secondary emission dispersion now correctly show a Gaussian profile. The thermal dispersion in electron mixes needs …
> Fix a bug in velocity dispersion sampling

- SKIRT/core/LineGasSecondarySource.cpp
- SKIRT/core/SpinFlipHydrogenGasMix.cpp
- SKIRT/core/SpinFlipHydrogenGasMix.hpp
- SKIRT/utils/Range.hpp
This update adds a full implementation of the `SpinFlipHydrogenGasMix` class, supporting the 21 cm line emission and self-absorption caused by the hyperfine structure "spin-flip" transition of neutral hydrogen atoms. The material mix expects the input model to define the total hydrogen number density, the neutral hydrogen fraction, and the gas metallicity and temperature. These properties and the local UV radiation field calculated by the simulation (taking into account dust extinction) are used to partition the neutral hydrogen in atomic and molecular fractions, and to then calculate the line luminosity en absorption coefficient. 
We employ the atomic/molecular partitioning scheme described by Gnedin and Kravtsov 2011. In contrast to many other observationally inspired …
> Add (poorly tested) implementation of 21 cm line emission and self-absorption 

- SKIRT/core/CompositeWavelengthGrid.cpp
- SKIRT/core/CompositeWavelengthGrid.hpp
- SKIRT/core/DisjointWavelengthGrid.cpp
- SKIRT/core/DisjointWavelengthGrid.hpp
- SKIRT/core/FileBorderWavelengthGrid.hpp
- SKIRT/core/FileWavelengthGrid.hpp
- SKIRT/core/ListBorderWavelengthGrid.hpp
- SKIRT/core/ListWavelengthGrid.hpp
- SKIRT/core/SimulationItemRegistry.cpp
The `CompositeWavelengthGrid` class aggregates a number of "child" wavelength grids configured by the user into a single, composite wavelength grid. All involved wavelength grids (i.e. all child grids and the composited grid) are disjoint wavelength grids, i.e. they inherit from the `DisjointWavelengthGrid` class. This essentially excludes grids based on broadband filters. 
The compositing procedure processes each child grid in order of occurrence, replacing any overlapped bins and splitting partially overlapped bins where needed. As long as all child wavelength ranges are mutually disjoint, the order in which the children are specified is irrelevant because the wavelength bins will be automatically sorted by the compositing process. As soon as there is overlap, however, …
> Add composite wavelength grid defined by aggregating a list of "child" wavelength grids

- .github/workflows/check-formatting.yml
This pull request serves to verify that the recently updated pull-request workflows still work after actually severing the ties with the external dependencies: the previously used action repository has been removed and the Travis CI integration has been disabled for the SKIRT repository.
Also, the name of the format checking workflow has been shortened to improve readability in the GitHub user interface.
> Verify workflows after severing ties with external dependencies

- SKIRT/core/FluxRecorder.cpp
- SKIRT/core/FluxRecorder.hpp
With this update, instruments configured with `recordComponents="true"` also record and output the transparent flux from secondary sources (i.e. media). The transparent flux is defined as the flux that would be received by the instrument if there were no attenuating media in the configuration.
**Compatibility**
The are no compatibility issues for the frames or cubes in FITS files. The instrument simply generates an extra output file, with a name ending in `_secondarytransparent.fits`. All other files retain the same name, including the `_transparent.fits` file providing the transparent flux from primary sources.
However, the **_extra column in SED output files_** does cause an incompatibility in certain cases. The `transparent secondary flux` column is added **_after_** …
> Instruments output transparent flux from secondary sources

- SKIRT/core/CylindricalVectorField.cpp
- SKIRT/core/CylindricalVectorField.hpp
- SKIRT/core/MediumVelocityPerCellProbe.cpp
- SKIRT/core/RadialVectorField.cpp
- SKIRT/core/RadialVectorField.hpp
With this update, the `RadialVectorField` and `CylindricalVectorField` classes offer options to specify a power-law dependence of the vector magnitude as a function of the radial distance. This allows configuring, for example, an outward radial velocity field with a given maximum velocity up to a given distance from the origin, and decreasing velocity from thereon according to a given power-law exponent. The behavior of the probes is fully upwards compatible with previous versions.
This update also corrects a bug in the `MediumVelocityPerCellProbe` class (incorrect output unit conversion).
**Motivation**
This feature was requested by user Đorđe Savić (@djsavic) for use with AGN models .
**Tests**
Existing functional tests still work; new tests have been added.
> Add power-law behavior to radial and rotational vector fields

- SKIRT/core/CarbonMonoxideGasMix.cpp
- SKIRT/core/CarbonMonoxideGasMix.hpp
- SKIRT/core/EmittingGasMix.cpp
- SKIRT/core/EmittingGasMix.hpp
- SKIRT/core/SimulationItemRegistry.cpp
- SKIRT/core/SpinFlipHydrogenGasMix.cpp
- SKIRT/core/SpinFlipHydrogenGasMix.hpp
- SKIRT/core/XRayAtomicGasMix.cpp
- SKIRT/core/XRayAtomicGasMix.hpp
- SMILE/serialize/XmlHierarchyCreator.cpp
- SMILE/wizard/DoubleListPropertyWizardPane.cpp
This update adds stub implementations (with empty functions and some documentation) for CO and X-ray atomic gas mixes. At this point, the new classes cannot be configured in the ski file (because they are not included in the simulation item registry).
**Motivation**
Adding these non-working implementations will facilitate joint development efforts.
> Add stub implementations for CO and X-ray gas mixes

- SKIRT/utils/SpatialGridPath.cpp
This update fixes a bug in the function that locates the next photon packet interaction point. If the requested (random) cumulative optical depth is zero, and the first segment of the photon path is outside of the spatial grid, then the function would locate the interaction point in the corresponding nonexistent cell, resulting in a fatal error "Cannot locate photon packet interaction point". This situation arises very occasionally when the source is outside of the spatial grid _and_ the total optical depth of the path is very low (<< 1) but not zero.  
After this update, the function will in this situation locate the interaction point in the first encountered nonempty cell, as it should.
**Motivation**
Even bugs that occur very rarely should be fixed :smirk:.
**Tests** …
> Fix very occasional fatal error when locating photon packet interaction point

- SKIRT/core/CarbonMonoxideGasMix.cpp
- SKIRT/core/CarbonMonoxideGasMix.hpp
- SKIRT/core/ComptonPhaseFunction.cpp
- SKIRT/core/ComptonPhaseFunction.hpp
- SKIRT/core/Configuration.cpp
- SKIRT/core/Configuration.hpp
- SKIRT/core/DipolePhaseFunction.cpp
- SKIRT/core/DipolePhaseFunction.hpp
- SKIRT/core/DustMix.cpp
- SKIRT/core/DustMix.hpp
- SKIRT/core/ElectronMix.cpp
- SKIRT/core/ElectronMix.hpp
- SKIRT/core/FragmentDustMixDecorator.cpp
- SKIRT/core/FragmentDustMixDecorator.hpp
- SKIRT/core/LyaNeutralHydrogenGasMix.cpp
- SKIRT/core/LyaNeutralHydrogenGasMix.hpp
- SKIRT/core/MaterialMix.hpp
- SKIRT/core/MediumSystem.cpp
- SKIRT/core/MediumSystem.hpp
- SKIRT/core/MonteCarloSimulation.cpp
- SKIRT/core/SpinFlipHydrogenGasMix.cpp
- SKIRT/core/SpinFlipHydrogenGasMix.hpp
- SKIRT/core/XRayAtomicGasMix.cpp
- SKIRT/core/XRayAtomicGasMix.hpp
- SKIRT/utils/PhotonPacket.cpp
- SKIRT/utils/PhotonPacket.hpp
With this update, the code properly supports models that include two or more media that may change a photon packet's wavelength during a scattering event, for example caused by the thermal velocity of the interacting particle. Previously, wavelength changes from multiple media would interfere, producing incorrect results.
**Motivation**
We can now combine, for example, gas with x-ray fluorescence (implemented as scattering) and electrons exhibiting Compton scattering in a simulation.
**Technical description**
This feature required two fairly technical adjustments to the code:
- All peel-off and random walk scattering operations for a given scattering event share the same randomly generated values including the interacting particle velocity. The related mechanism has been …
> Allow multiple media components to change the wavelength during scattering

- SKIRT/core/SiteListTreePolicy.cpp
The `SiteListTreePolicy` class reported an incorrect completion percentage when subdividing extra spatial tree levels. This is now fixed.
> Fix minor logging issue in SiteListTreePolicy class

- SKIRT/core/CarbonMonoxideGasMix.cpp
- SKIRT/core/CarbonMonoxideGasMix.hpp
- SKIRT/core/DynamicStateRecipe.cpp
- SKIRT/core/DynamicStateRecipe.hpp
- SKIRT/core/MaterialMix.cpp
- SKIRT/core/MaterialMix.hpp
- SKIRT/core/MediumSystem.cpp
- SKIRT/core/MediumSystem.hpp
- SKIRT/core/MonteCarloSimulation.cpp
- SKIRT/core/SpinFlipHydrogenGasMix.cpp
- SKIRT/core/SpinFlipHydrogenGasMix.hpp
This pull request adds a convergence mechanism for iterative semi-dynamic medium state updates, similar to the mechanism already implemented for dynamic medium state updates.
**Motivation**
The `CarbonMonoxideGasMix` class calculates the electronic energy level populations (from which the emitted line spectrum is derived) during iterative semi-dynamic medium state updates, requiring a mechanism to determine convergence. In the future, similar calculations for other molecular or atomic lines will require such a mechanism as well. 
**Tests**
All functional tests still work without change, although the order of log messages related to convergence has changed in some cases. The new mechanism has been tested with a stub implementation of the `CarbonMonoxideGasMix` class. It …
> Add convergence mechanism for iterative semi-dynamic medium state updates

- SKIRT/core/LaunchedPacketsProbe.cpp
- SKIRT/core/LaunchedPacketsProbe.hpp
- SKIRT/core/SecondarySourceSystem.cpp
- SKIRT/core/SecondarySourceSystem.hpp
- SKIRT/core/SourceSystem.cpp
- SKIRT/core/SourceSystem.hpp
This pull request extends the `LaunchedPacketsProbe` to include columns for secondary sources, if applicable. Also, it is now possible to include multiple `LaunchedPacketsProbe` instances in a configuration, for example to cover several distinct wavelength ranges.
**Motivation**
Exposing this information will help fine-tune secondary emission bias factors, for example in simulations with both dust and gas emission.
**Tests**
Existing functional tests still work. The column headers of the `LaunchedPacketsProbe` probe output have been updated to differentiate between primary and secondary emission.
> Include secondary emission in LaunchedPacketsProbe

- SKIRT/core/DustMix.cpp
- SKIRT/core/DustMix.hpp
In the X-ray wavelength range, dust grains exhibit extreme forward scattering with asymmetry parameter values very close to unity. Calculating the value of and sampling from the Henyey-Greenstein (HG) phase function becomes numerically unstable for |g| > 1 - 1e-6. Therefore, the implementation clips any larger values to that limit.
More annoyingly, the bias weights for scattering peel-off photon packets can become very large, causing unacceptably high noise levels in the fluxes recorded by instruments. To address this situation, we average the peel-off bias weight for a photon packet sent to an instrument over a portion of the phase function, as opposed to taking the value at a given angle. This introduces a certain amount of blur in recorded fluxes, while simultaneously …
> Add workaround for extreme forward scattering by dust in the X-ray regime

- SKIRT/core/MeanInterstellarDustMix.hpp
- SKIRT/resources/ExpectedResources.txt
The optical properties of the `MeanInterStellarDustMix` as downloaded from the Draine web site are given down to wavelengths as short as 1e-4 micron, i.e. well into the soft X-ray wavelength range. The tabulated cross sections seem to be very accurate, however the average scattering angle cosine values in this regime are unrealistic (e.g., equal to one for the shortest wavelengths).
Draine 2003c (ApJ, 98, 1026–1037) presents experimental data for the phase function in the soft X-ray wavelength range and proposes an analytical phase function to model the observed extreme forward scattering. Rather than attempting to implement this phase function, we approximate it through the Henyey-Greenstein phase function just as we do for other wavelengths. For wavelengths shorter than …
> Adjust MeanInterStellarDustMix scattering asymmetry parameter for X-ray wavelengths

- SKIRT/core/XRayAtomicGasMix.cpp
- SKIRT/core/XRayAtomicGasMix.hpp
This update adds the effects of scattering by bound electrons to the `XRayAtomicGasMix` material mix (next to photo-absorption and fluorescence, which were already implemented).
Electrons bound to the atoms in the gas scatter incoming X-ray photons with a cross section that is very close to that of free electrons. For lower X-ray photon energies, the phase function for the two processes differs substantially. However, in that regime, scattering is totally dominated by photo-absorption, so it does not seem important to accurately model the scattering process. For higher X-ray photon energies, where the scattering cross section does become significant, bound-electron scattering closely approaches free-electron scattering. The implementation thus simply assumes that each of …
> Add scattering by bound electrons to X-ray atomic gas

- SKIRT/core/TextInFile.cpp
Some standard library implementations do not support reading NaN or Inf values from a text input stream, while others do. This update provides backup support for NaN values in the `TextInFile` class on those platforms that don't support them automatically. The error messages issued by the `TextInFile` class are now also more informative.
_Note_: supporting infinite values is more complex because of the need for handling the negative sign which may be already consumed by the stream, and, at least for now, we don't need infinite values anyway.
**Motivation**
The resource files for anomalous Rayleigh scattering used by the `XRayAtomicGasMix` class contain NaN values.
**Tests**
Tested the `XRayAtomicGasMix` class with GCC on Ubuntu as well as Clang on Mac OS.
> Support NaN values in column text files

- SKIRT/core/XRayAtomicGasMix.cpp
- SKIRT/core/XRayAtomicGasMix.hpp
This pull request modifies the X-ray atomic gas mix in two ways:
- New photo-absorption cross sections from Verner et al. 1996 for the outer shell electrons.
- New option to ignore bound-electron scattering when using the atomic gas mix in SKIRT.
**Motivation**
Both updates were needed to benchmark our code against the standard XSPEC spectral models (PHABS, VPHABS, PEXMON, PEXRAV,...). With the new cross sections, we mimic the XSPEC cross section settings "xsect vern". As these models do not take bound-electron scattering in account, we need this option to ignore bound-electron scattering in SKIRT.
**Tests**
After these two updates, we are able to match the XSPEC photo-absorption output perfectly with SKIRT, both for all elements together (PHABS) and for the individual …
> Updated photo-absorption cross sections and option to ignore bound-electron scattering

- SKIRT/core/Configuration.cpp
- SKIRT/core/Configuration.hpp
- SKIRT/core/ConvergenceInfoProbe.cpp
- SKIRT/core/FluxRecorder.cpp
- SKIRT/core/MaterialMix.cpp
- SKIRT/core/MaterialMix.hpp
- SKIRT/core/MediumSystem.cpp
- SKIRT/core/MediumSystem.hpp
- SKIRT/core/MonteCarloSimulation.cpp
- SKIRT/core/MonteCarloSimulation.hpp
- SKIRT/core/PhotonPacketOptions.hpp
- SKIRT/core/SimulationItemRegistry.cpp
- SKIRT/core/TrivialGasMix.cpp
- SKIRT/core/TrivialGasMix.hpp
- SKIRT/core/XRayAtomicGasMix.hpp
- SKIRT/utils/SpatialGridPath.cpp
- SKIRT/utils/SpatialGridPath.hpp
This update introduces the explicit absorption technique as an optional variation of the Monte Carlo photon packet life cycle. This allows handling materials that exhibit stimulated emission, which may lead to negative  extinction cross sections (and correspondingly, negative optical depths). To the best of our knowledge, this technique has not yet been described in the literature; we plan to rectify that situation in the coming months. At heart, the idea is to use the scattering optical depth (which is always positive) instead of the extinction optical depth (which may be negative) for locating the next interaction point along a photon packet path.
The update also adds the new `TrivialGasMix` class to help construct basic test models that include materials with stimulated …
> Introduce optional explicit absorption in the photon packet life cycle

- SKIRT/core/InstrumentWavelengthGridProbe.cpp
- SKIRT/core/XRayAtomicGasMix.cpp
This update fixes two bugs:
- In wavelength grid probes (for instruments or other wavelength grids), when using energy or frequency output units, the wavelength bin width was incorrect. 
- In `XRayAtomicGasMix`, the photo-absorption cross section parameters were not correctly loaded from the resource file.
**Motivation**
We like fixing bugs 😄
> Fix wavelength bin widths in energy units and X-ray cross sections

- SKIRT/core/ClumpyGeometryDecorator.cpp
- SKIRT/core/ClumpyGeometryDecorator.hpp
- SKIRT/core/Random.cpp
- SKIRT/core/Random.hpp
By default, the `ClumpyGeometryDecorator` class uses the standard random generator also used by other classes during setup. Multiple occurrences of the ClumpyGeometryDecorator in a given ski file will produce a different set of clump positions, because consecutive portions of the pseudo-random sequence are being employed. While this is usually just fine, in some models one might want to line up, for example, the clumps in a medium distribution with those in a source distribution.
Therefore, this update adds a _seed_ property to the `ClumpyGeometryDecorator` . If a nonzero value is specified for this _seed_ property, the clump positions are generated using a temporary random number generator initialized with that seed. Configuring the same seed for two …
> Allow source/medium-colocated clumps in clumpy decorator

- SKIRT/core/ImportedMediumDensityProbe.cpp
- SKIRT/core/ImportedMediumMetallicityProbe.cpp
- SKIRT/core/ImportedMediumTemperatureProbe.cpp
- SKIRT/core/ImportedMediumVelocityProbe.cpp
- SKIRT/core/ImportedSourceAgeProbe.cpp
- SKIRT/core/ImportedSourceAgeProbe.hpp
- SKIRT/core/ImportedSourceDensityProbe.cpp
- SKIRT/core/ImportedSourceDensityProbe.hpp
- SKIRT/core/ImportedSourceLuminosityProbe.cpp
- SKIRT/core/ImportedSourceLuminosityProbe.hpp
- SKIRT/core/ImportedSourceMetallicityProbe.cpp
- SKIRT/core/ImportedSourceMetallicityProbe.hpp
- SKIRT/core/ImportedSourceVelocityProbe.cpp
- SKIRT/core/ImportedSourceVelocityProbe.hpp
- SKIRT/core/ImportedSourceWeightedProbe.cpp
- SKIRT/core/ImportedSourceWeightedProbe.hpp
- SKIRT/core/InputModelFormProbe.cpp
- SKIRT/core/InputModelFormProbe.hpp
- SKIRT/core/ProbeFormBridge.cpp
- SKIRT/core/ProbeFormBridge.hpp
- SKIRT/utils/EntityCollection.cpp
- SKIRT/utils/EntityCollection.hpp
With this update, the probes for imported sources now always produce just a single output file, aggregating the requested information for all imported sources in the simulation's configuration (accumulating or averaging depending on the quantity being probed). This is an incompatible change, as detailed below.
**Motivation**
Calculating mass-averaged quantities (such as metallicity or age) over an individual source does not make any sense. Specifically, if there are multiple sources, it is impossible to calculate the overall average based on the individual averages per component. The previously produced information was thus essentially useless in this context. The issue is less annoying for accumulated quantities (such as luminosity), but it seems more meaningful to handle …
> Imported source probes always use system aggregation

- SKIRT/core/Cylinder2DSpatialGrid.cpp
- SKIRT/core/Cylinder2DSpatialGrid.hpp
- SKIRT/core/SpatialGrid.cpp
- SKIRT/core/SpatialGrid.hpp
- SKIRT/core/Sphere1DSpatialGrid.cpp
- SKIRT/core/Sphere1DSpatialGrid.hpp
- SKIRT/core/Sphere2DSpatialGrid.cpp
- SKIRT/core/Sphere2DSpatialGrid.hpp
- SKIRT/core/VoronoiMeshSpatialGrid.cpp
- SKIRT/core/VoronoiMeshSpatialGrid.hpp
This update addresses two issues in spherical and cylindrical spatial grids (`Sphere1DSpatialGrid`, `Sphere2DSpatialGrid`, `Cylinder2DSpatialGrid`).
- Random positions generated for these grids were located in the correct cell but were not uniformly distributed within the cell. This is now fixed. This issue affects two areas in simulations using one of these grids: sampling the input model density distribution and choosing the originating positions for photon packets during secondary emission from the medium. Although the previous behavior was incorrect, the effect is minor as long as the spatial domain is sufficiently resolved (so that each cell is small relative to the model size).
- The cell diagonal function now returns a more meaningful value for these grids. This …
> Random points and diagonals in spherical and cylindrical grids

- SKIRT/core/Configuration.hpp
- SKIRT/core/Cylinder2DSpatialGrid.cpp
- SKIRT/core/Cylinder2DSpatialGrid.hpp
- SKIRT/core/MolecularLineGasMix.cpp
- SKIRT/core/MolecularLineGasMix.hpp
- SKIRT/core/NonLTELineGasMix.cpp
- SKIRT/core/NonLTELineGasMix.hpp
- SKIRT/core/SimulationItemRegistry.cpp
- SKIRT/core/SkirtUnitDef.cpp
- SKIRT/core/SpatialGrid.cpp
- SKIRT/core/SpatialGrid.hpp
- SKIRT/core/Sphere1DSpatialGrid.cpp
- SKIRT/core/Sphere1DSpatialGrid.hpp
- SKIRT/core/Sphere2DSpatialGrid.cpp
- SKIRT/core/Sphere2DSpatialGrid.hpp
- SKIRT/core/VoronoiMeshSpatialGrid.cpp
- SKIRT/core/VoronoiMeshSpatialGrid.hpp
- SKIRT/resources/ExpectedResources.txt
This update adds the `NonLTELineGasMix` class, which describes the material properties related to selected transitions in    selected molecules and atoms. For each supported species, the current implementation includes a number of rotational energy levels (quantum number J) at the base vibrational level (quantum number v=0) for molecules and electronic energy levels and hyperfine split levels for atoms, and supports the allowed transitions between these levels. Vibrational energy levels and the corresponding rovibrational transitions may be added later. The class properties allow configuring the species and the number of transitions to be considered.
For each supported transition, the emission luminosity and absorption opacity in a given cell are determined from the gas …
> Support self-consistent non-LTE line transfer for selected transitions and species

- SKIRT/core/DisjointWavelengthGrid.cpp
- SKIRT/core/DisjointWavelengthGrid.hpp
- SKIRT/core/FileBorderWavelengthGrid.cpp
- SKIRT/core/FileBorderWavelengthGrid.hpp
- SKIRT/core/ListBorderWavelengthGrid.cpp
- SKIRT/core/ListBorderWavelengthGrid.hpp
This update provides the `FileBorderWavelengthGrid` and `ListBorderWavelengthGrid` classes with the option to 
include the characteristic wavelength for each bin in the wavelength list, interleaved with the border wavelengths (i.e., borders and characteristic wavelengths alternate). A zero characteristic wavelength indicates a segment that is not part of the grid, i.e. that lies between two non-adjacent bins. In other words, this option allows to arbitrarily place characteristic wavelengths within each bin and to specify intermediate wavelength ranges that are not covered by any bin.
**Motivation**
Simulations that include line emission often need wavelength grids with a sequence of bins for each line (and no bins in between). It is sometimes more convenient to generate …
> Extra flexibility for wavelength grids loaded from file or list

- SKIRT/core/NonLTELineGasMix.cpp
- SKIRT/core/NonLTELineGasMix.hpp
This update introduces two expert options to the `NonLTELineGasMix` class:
- optionally store the mean radiation field intensities in the medium state, so that this information can be probed. 
- allows the initial level populations to be loaded from a file that is typically produced by a probe in a previous simulation.
Use these options with care; see the documentation of the `NonLTELineGasMix` class.
**Motivation**
- The mean radiation field intensities can form a relevant diagnostic to assess the level of Monte Carlo noise in the simulation or to evaluate iterative convergence. Previously, these values were always stored; this new option by default avoids the corresponding memory usage but allows enabling the capability if needed.
- By default, the level populations are …
> Add some expert options to NonLTELineGasMix

- SKIRT/core/MediumSystem.cpp
- SKIRT/core/MonteCarloSimulation.cpp
This update fixes a bug that caused a segmentation fault when using XRayAtomicGasMix outside of its wavelength range (e.g., above 500 keV) and in combination with other media. Specifically, the framework no longer calls the material mix scattering peel-off function if the scattering cross section of the material for the photon packet's wavelength is zero.
**Tests**
A functional test was added to reproduce this particular issue.
> Fix bug when using XRayAtomicGasMix outside of its wavelength range

- SKIRT/core/SpatialGridWhenFormProbe.hpp
- SKIRT/core/SpecialtyWhenProbe.hpp
- SKIRT/main/SkirtCommandLineHandler.cpp
- SKIRT/main/SkirtCommandLineHandler.hpp
- SKIRT/mpi/ProcessManager.cpp
- SKIRT/mpi/ProcessManager.hpp
After this update, if SKIRT runs with multiple processes and the -v command line option is specified, the log files for each individual process will include diagnostic messages bracketing all MPI operations. This should facilitate debugging problems with inter-process communication.
**Motivation**
Sometimes, a multi-process simulation hangs indefinitely, apparently at a point where MPI communication is happening or should happen. These diagnostic messages will hopefully help us understand what is going on when this happens.
> Add diagnostic logging for MPI operations

- SKIRT/core/ProbeFormBridge.cpp
- SKIRT/core/ProbeFormBridge.hpp
- SKIRT/core/SecondaryLineLuminosityProbe.cpp
- SKIRT/core/SecondaryLineLuminosityProbe.hpp
- SKIRT/core/SimulationItemRegistry.cpp
- SKIRT/core/SkirtUnitDef.cpp
- SKIRT/core/Units.cpp
- SKIRT/core/Units.hpp
The new `SecondaryLineLuminosityProbe` class probes the line luminosities of secondary sources as discretized on the spatial grid of the simulation. For each relevant medium component, it outputs the intrinsic bolometric, line-profile-integrated luminosities for each of the lines from which the medium emits.
The probe can be used with any Form subclass. When associated with a form that samples the luminosity in a spatial grid cell or for a linear or planar cut, the probe outputs a bolometric luminosity volume density (with SI units of W/m3). When associated with a form that projects the luminosity along a path, the probe outputs a bolometric luminosity surface (or column) density (with SI units of W/m2).
**Motivation**
This functionality was suggested by @Koseimatsu for …
> Add probe for line luminosity during secondary emission

- SKIRT/core/AllSkyProjectionForm.cpp
- SKIRT/core/ParallelFactory.cpp
- SKIRT/core/ParallelFactory.hpp
- SKIRT/core/ParallelProjectionForm.cpp
- SKIRT/core/PlanarCutsForm.cpp
- SKIRT/mpi/ProcessManager.cpp
- SKIRT/mpi/ProcessManager.hpp
The new imaging form probes (`AllSkyProjectionForm`, `ParallelProjectionForm`, `PlanarCutsForm`, `DefaultCutsForm`, `ConvergenceCutsProbe`) use distributed parallelization (i.e. all processes cooperate) to construct the probed image(s). A problem with the synchronization between processes sometimes caused the code to "hang" indefinitely. This should now be fixed.
As an aside, a few lines of obsolete code were removed in the `ParallelFactory` class. This should not affect the operation of the code.
**Context**
The problem was related to the `ProcessManager::sumToRoot()` function, which was previously used only for instruments and now also for the probes listed above. Because nonroot processes do not receive any data in this function, if the MPI implementation buffers the …
> Fix multi-process hang in imaging form probes

- SKIRT/core/DensityTreePolicy.hpp
- SKIRT/core/SpatialGridWhenFormProbe.hpp
- SKIRT/core/TemperatureProbe.cpp
- SKIRT/core/TemperatureProbe.hpp
This update fixes two very minor issues discovered while writing documentation for the web site:
- Improve default value for when the temperature probe is performed (after run for dust, after setup for other media).
- Suppress octree subdivision options for media types that are not included in the simulation.
> Some very minor fixes

- SKIRT/voro/cell.cc
- SKIRT/voro/cell.hh
- SKIRT/voro/common.cc
- SKIRT/voro/common.hh
- SKIRT/voro/container.cc
- SKIRT/voro/container.hh
- SKIRT/voro/container_prd.cc
- SKIRT/voro/container_prd.hh
- SKIRT/voro/unitcell.cc
- SKIRT/voro/unitcell.hh
- SKIRT/voro/v_compute.cc
- SMILE/fundamentals/Basics.hpp
- SMILE/fundamentals/StringUtils.cpp
- SMILE/fundamentals/System.cpp
**Motivation**
Recent compiler versions produce a warning about the use of the standard library function `sprintf` because the function does not know the length of its output buffer and thus may write past the end of the provided buffer.
This pull request represents a technical update to avoid these warnings (no features are introduced or changed):
- in our own code, the few uses of `sprintf` are replaced by the use of `snprintf`, a safe alternative introduced to the standard library some time ago.
- in the Voro++ code, all functions related to text output are removed (these functions heavily use `sprintf` but are never invoked in SKIRT).
**Tests**
All functional tests still work.
> No longer use unsafe function sprintf

- SKIRT/core/NonLTELineGasMix.cpp
- SKIRT/core/NonLTELineGasMix.hpp
** Motivation**
The absorption opacity returned by the `NonLTELineGasMix` class is negative in case the medium exhibits stimulated emission. The explicit absorption technique (see the `MonteCarloSimulation` class) supports the corresponding negative optical depths along a photon path. However, numerical problems arise if the negative optical depth magnitude becomes too high. This may happen, for example, as a result of Monte Carlo noise, or in the early stages when a simulation has not yet converged.
** Description**
With this update, the `NonLTELineGasMix` class imposes a user-configurable lower limit on the (negative) optical depth along a cell diagonal before returning an absorption opacity. The default optical depth limit is -2.
**Tests**
Verified that an example simulation no longer …
> Limit negative optical depth for NonLTE line gas mix

- CMakeLists.txt
- MakeUp/main/CMakeLists.txt
- SMILE/wizard/BasicChoiceWizardPane.cpp
- SMILE/wizard/BasicChoiceWizardPane.hpp
- SMILE/wizard/BoolPropertyWizardPane.cpp
- SMILE/wizard/BoolPropertyWizardPane.hpp
- SMILE/wizard/CMakeLists.txt
This pull request updates the CMake build procedure for MakeUp to support both Qt5 and Qt6 framework versions, and replaces the use of some obsolete signals in the MakeUp wizard with equivalent code that works on both Qt5 and Qt6.
**Motivation**
This allows MakeUp to be used with Qt6, which has been available for quite a while now.
> Allow MakeUp to be built with Qt6 (as well as Qt5)

- SKIRT/core/AnnulusGeometry.cpp
- SKIRT/core/AnnulusGeometry.hpp
- SKIRT/core/Cylinder2DSpatialGrid.hpp
- SKIRT/core/DonutGeometry.cpp
- SKIRT/core/DonutGeometry.hpp
- SKIRT/core/SimulationItemRegistry.cpp
This update adds two basic 2D geometries to the built-in library:
- The `AnnulusGeometry` describes a uniform cylindrical disk with a cylindrical hole.
- The `DonutGeometry` describes an axisymmetric ring torus (i.e. a doughnut) of uniform density.
**Motivation**
These geometries are often used to model medium components of active galactic nuclei. However, they are implemented as generic elements of the SKIRT geometry library and can thus be used to model both media and sources.
**Tests**
New functional tests were added.
**Context**
These geometries were contributed by @BertVdM.
> Add annulus and donut geometries

- SKIRT/core/MultiGrainDustMix.cpp
- SKIRT/fitsio/group.c
- SKIRT/voro/cell.cc
The new C/C++ compiler installed by Xcode 13.2 on macOS introduces a few changes that require adjustments:
- The `macintosh` macro is no longer supported. This macro was used in one of the FITSIO sources included with SKIRT and is now replaced by a more modern mechanism to detect macOS at compile time.
- The new compiler issues a warning for variables that are initialized and updated but never actually used. These redundant variables have been removed from the code (in two places).
**Motivation**
The first issue caused compilation to fail and the second issue caused potentially confusing warnings.
**Tests**
All functional tests still work.
> Minor adjustments for compatibility with new compiler on macOS

- SKIRT/core/XRayAtomicGasMix.cpp
- SKIRT/core/XRayAtomicGasMix.hpp
- SKIRT/resources/ExpectedResources.txt
Extended the XRayAtomicGasMix medium (modelling neutral gas atoms with Z < 31) with all fluorescent lines that have line energies above 0.1 keV. Included 20 fluorescent lines per element (i.e. all possible lines, except for the three L->L lines that are always < 0.2 keV, and thus outside the detectable X-ray range with XMM, Chandra, XRISM, Athena,...): Ka2, Ka1, Kb3, KB1, Kb5II, KB5I, Lb4, Lb3, Lb10, Lb9, Le, Lb17, Lb1, Lg5, Ll, Lt, Ls, La2, La1, Lb6. The yields of all lines towards L2 and L3 are corrected with a factor 2/6 and 4/6, respectively, to account for the total L2,3 photo- absorption cross section by Verner et al. (1995, 1996) used in SKIRT.
**Motivation**
Many of these new lines will be detected with upcoming microcalorimeter missions such as XRISM and Athena, …
> Add extra fluorescent lines to XRayAtomicGasMix

- SKIRT/core/ComptonPhaseFunction.cpp
- SKIRT/core/ComptonPhaseFunction.hpp
- SKIRT/core/ElectronMix.cpp
- SKIRT/core/ElectronMix.hpp
- SKIRT/core/XRayAtomicGasMix.cpp
- SKIRT/core/XRayAtomicGasMix.hpp
- SKIRT/utils/StokesVector.cpp
- SKIRT/utils/StokesVector.hpp
With this update, we support polarization for Compton scattering by free electrons represented by the `ElectronMix` class or as part of the `XRayAtomicGasMix` class. As a result, both media types now support polarization across the full wavelength range (i.e. for both Thomson and Compton scattering). 
Important limitation: the XRayAtomicGasMix class supports polarization only in the approximation where the bound electrons are treated as free electrons.
**Motivation**
Polarization at high energies is relevant for simulations of certain X-ray observations.
**Tests**
The existing functional tests still run correctly. However, the new functionality has been not yet been tested extensively.
_Use with care!_
> Support polarization for Compton scattering

- SKIRT/core/ComptonPhaseFunction.cpp
- SKIRT/core/ComptonPhaseFunction.hpp
- SKIRT/core/DipolePhaseFunction.cpp
- SKIRT/core/DipolePhaseFunction.hpp
- SKIRT/core/DustMix.cpp
- SKIRT/core/DustMix.hpp
- SKIRT/core/ElectronMix.hpp
- SKIRT/core/FragmentDustMixDecorator.hpp
- SKIRT/core/LyaNeutralHydrogenGasMix.hpp
- SKIRT/core/MaterialMix.hpp
- SKIRT/core/MediumSystem.cpp
- SKIRT/core/TrivialGasMix.cpp
- SKIRT/core/XRayAtomicGasMix.cpp
- SKIRT/core/XRayAtomicGasMix.hpp
- SKIRT/utils/StokesVector.cpp
- SKIRT/utils/StokesVector.hpp
This update slightly improves the code and documentation for the scattering peel-off implementation in the various material mixes. The functionality has not changed (at least, that is the intention).
**Motivation**
It should now be more obvious to the reader that the Stokes vector components other than the intensity do not need to be updated for a "scattering" process that always emits isotopic and unpolarized radiation.
> Minor scattering peel-off code improvement

- SKIRT/core/BegemannPorousAluminaGrainComposition.hpp
- SKIRT/core/DorschnerOlivineGrainComposition.hpp
- SKIRT/core/HofmeisterPericlaseGrainComposition.hpp
- SKIRT/resources/ExpectedResources.txt
The files of optical properties of Periclase and Porous Alumina calculated considering spherical grains were replaced by files with optical properties considering grains described by a continuous distribution of elliposids. For the Olivine file, only information was added in the commented section, where it is specified that the grains are spherical.
> Corrections to the optical prop files of the new composition for AGN dust

- SKIRT/core/SimulationItemRegistry.cpp
- SKIRT/core/ToddlersSED.cpp
- SKIRT/core/ToddlersSED.hpp
- SKIRT/core/ToddlersSEDFamily.cpp
- SKIRT/core/ToddlersSEDFamily.hpp
- SKIRT/resources/ExpectedResources.txt
This update adds the TODDLERS family of star-forming region SEDs parameterized on age, metallicity, star formation efficiency, and cloud number density. This SED template library has been developed by @anandutsavkapoor and is described in detail by Kapoor et al. in the manuscript submitted to MNRAS on May 26, 2023.
The `ToddlersSEDFamily` class requires the data contained in the TODDLERS resource pack, which can be installed through the `./downloadResources.sh` procedure.
**Motivation**
When compared to the previous treatment of star-forming regions in SKIRT, TODDLERS shows a better agreement with low-redshift observational data in the IR wavelength range, while offering a more comprehensive line-emission support. This paves the way for a variety of applications using …
> Add TODDLERS star-forming region SED template library

- SKIRT/core/ToddlersSEDFamily.hpp
The TODDLERS documentation mentions SFE in percentages while the SED lookup tables use fractional values. Changing the documentation avoids this confusion.
Description
Minor change in the documentation which replaces SFE percentage values with fractional values.
Motivation
To avoid confusion when using the TODDLERS SEDs, a non-fractional value of SFE will force the use of the highest available value in the tables.
Tests
No tests required
> Update ToddlersSEDFamily documentation

- SKIRT/core/NonLTELineGasMix.cpp
- SKIRT/core/NonLTELineGasMix.hpp
- SKIRT/resources/ExpectedResources.txt
With this pull request, the `NonLTELineGasMix` class supports the following new species:
- Hydroxyl radical with hyperfine splitted levels, in addition to the previously offered Hydroxyl radical that does _not_ include hyperfine splitted levels.
- Molecular hydrogen, with a fixed ratio of ortho to para flavors of 3 to 1.
For more information, refer to the `NonLTELineGasMix` class documentation.
To support these new species, users must download version 5 of the `AtomsMolecules` resource pack in addition to building the updated code.
**Tests**
Existing tests still work without change; two new basic tests were added for the new species.
**Context**
The data and suggested code changes for this update were provided by @Koseimatsu. Also see pull request …
> Support two new species for non-LTE line transfer

- SKIRT/core/Configuration.cpp
- SKIRT/core/MonteCarloSimulation.cpp
- SKIRT/core/MonteCarloSimulation.hpp
- SKIRT/core/PhotonPacketOptions.hpp
**Motivation**
The photon life cycle without forced scattering terminates only after the photon packet escapes from the model. However, in some cases, the luminosity of a photon packet may fall to zero long before it actually escapes from the model. A zero-luminosity packet can no longer make any contributions to the simulation results, so it does not make sense to continue tracking its path through the medium.
**Context**
This issue was reported by @BertVdM. In the provided example (a torus of `XRayAtomicGasMix` gas with a central point source) some photon packets would experience more than 25 million scattering events before escaping from the model, most of which after reaching zero luminosity.
With this pull request:
- The photon life cycle without forced scattering …
> Fix performance issue in photon life cycle without forced scattering

- SKIRT/resources/ExpectedResources.txt
This pull request updates the resource files for the optical properties of the dust mixes in the ExtraDust resource pack, i.e. `BegemannPorousAlumina`, `DorschnerOlivine`, and `HofmeisterPericlase`, typically used for AGN models.
The Qabs and Qsca values for each dust species for each grain size were extrapolated to wavelengths from 1e-3 to 1e3
microns following a rough approximation of the behavior of the Qabs and Qsca. Previously the optical properties did not
cover this wavelength range and the outer regions were filled by SKIRT with a constant value.
**Motivation**
Allow simulations to use the more extended wavelength range.
**Context**
These data were prepared and provided by @oura71 .
> Extrapolated optical properties for AGN dust mixes

- SKIRT/core/DensityTreePolicy.cpp
- SKIRT/core/DensityTreePolicy.hpp
- SKIRT/core/NestedDensityTreePolicy.cpp
- SKIRT/core/NestedDensityTreePolicy.hpp
- SKIRT/core/SimulationItemRegistry.cpp
- SKIRT/core/TreePolicy.hpp
- SKIRT/utils/Box.hpp
- slight changes to `DensityTreePolicy` & `TreePolicy` to conform with the new `NestedDensityTreePolicy`
- added extra `contains` & `intersects` to Box
**Motivation**
Allows for using nested OctTree / BinTree for greater refinement in user chosen regions
**Tests**
Tested for both OctTree and BinTree with different refinement levels and DensityTree properties such as `maxDustFraction`
> Add Nested Density Tree Policy

- SKIRT/core/ParallelProjectionForm.cpp
- SKIRT/core/ParallelProjectionForm.hpp
This pull request adds the possibility to oversampling to the ParallelProjectionForm. 
**Motivation**
The parallel projection for the probes was based on a simple algorithm that just integrated the quantity to be projected along a single line from the centre of each pixel of the array in the projection plane. This is not ideal if the pixels are relatively large compared to the size of the particles (in the case of smoothed particles). The new version allows for oversampling: instead of integrating along a single line, each pixel is now subdivided into N x N subpixels, and the result is the average of the integrations along all these lines. The oversampling rate N is a parameter that can be chosen by the user.
**Tests**
Tests were done with a simple model (a single SPH …
> Adds possibility to oversampling to ParallelProjectionForm

- SKIRT/core/Configuration.hpp
- SKIRT/core/MaterialMix.cpp
- SKIRT/core/MaterialMix.hpp
- SKIRT/core/MediumState.cpp
- SKIRT/core/MediumState.hpp
- SKIRT/core/MediumSystem.cpp
- SKIRT/core/MediumSystem.hpp
- SKIRT/core/MonteCarloSimulation.cpp
- SKIRT/core/NonLTELineGasMix.cpp
- SKIRT/core/NonLTELineGasMix.hpp
The `NonLTELineGasMix` class now offers an additional convergence criterion based on the global level populations.  Specifically, the _maxChangeInGlobalLevelPopulations_ property specifies the maximum relative change between consecutive iterations in the total level populations accumulated over the complete spatial domain. The new criterion complements or, if so desired, replaces the existing criterion based on statistics per spatial cell. Both criteria must be satisfied simultaneously; however, the user can effectively disable a criterion by specifying very liberal maximum values.
**Motivation**
For complex models, the Monte Carlo noise inherent to the SKIRT simulation mechanism can cause the level populations in individual cells to fluctuate quite significantly between …
> Add convergence criterion to NonLTELineGasMix using global level populations

- SKIRT/core/DensityProbe.cpp
- SKIRT/core/DensityProbe.hpp
- SKIRT/core/FragmentDustMixDecorator.cpp
- SKIRT/core/FragmentDustMixDecorator.hpp
- SKIRT/core/OpacityProbe.cpp
- SKIRT/core/OpacityProbe.hpp
- SKIRT/core/TemperatureProbe.hpp
In analogy with the feature recently added for temperature probing, this update adds `Fragment` aggregation to the `DensityProbe` and `OpacityProbe` classes. This allows producing information for the individual grain populations formed by the `FragmentDustMixDecorator` class.
**Motivation**
This feature is especially meaningful for evaluating the results of simulations that include dust destruction.
It was requested by user Niklas Moszczynski.
**Tests**
Two new functional tests were added.
> Allow probing density and opacity for individual grain populations

- SKIRT/core/SimulationItemRegistry.cpp
- SKIRT/core/SpinFlipAbsorptionMix.cpp
- SKIRT/core/SpinFlipAbsorptionMix.hpp
- SKIRT/core/SpinFlipSEDFamily.cpp
- SKIRT/core/SpinFlipSEDFamily.hpp
This update adds a new simulation flow for the 21-cm spin-flip transition, using the SKIRT ExtinctionOnly simulation mode: The emission of 21-cm photons happens as primary emission (SpinFlipSEDFamily based on LyaSEDFamily), and HI self-absorption happens in the medium (SpinFlipAbsorptionMix based on ElectronMix). 
**Motivation**
For a medium in which the atomic hydrogen distribution is known, the previous simulation flow which required hydrogen partitioning based on the UV radiation field is outdated. When the atomic hydrogen distribution is known a priori (i.e. before running SKIRT), then the ExtinctionOnly mode is appropriate.
**Tests**
For the configuration of a single emitting point source and a single absorbing SPH particle (offset to the point source), the SKIRT …
> Add separate SpinFlip emission/absorption classes

- SKIRT/core/SpinFlipAbsorptionMix.cpp
- SKIRT/core/SpinFlipAbsorptionMix.hpp
- SKIRT/core/SpinFlipHydrogenGasMix.cpp
- SKIRT/core/SpinFlipHydrogenGasMix.hpp
- SKIRT/core/SpinFlipSEDFamily.cpp
- SKIRT/core/SpinFlipSEDFamily.hpp
- SKIRT/utils/Constants.hpp
**Motivation and description**
The `SpinFlipHydrogenGasMix` class uses a hydrogen partitioning scheme to split neutral hydrogen (typically available from hydrodynamical cosmological simulations) into its atomic and molecular constituents. The current implementation (before this update) uses the _local_ (based on volumetric gas density) partitioning scheme of Gnedin & Kravtsov 2011, ApJ, 728, 88. However, this scheme produces HI column densities in excess of the typically observed threshold, which is probably related to the usage of volumetric densities. 
The default approach in the literature (e.g. Diemer et al., 2018, ApJS, 238, 33 and Gebek et al., 2023, MNRAS, 521, 5645) is to use column-density based partitioning schemes. To conform to this default approach which seems to yield more …
> Update atomic/molecular partitioning scheme in SpinFlipHydrogenGasMix

- SKIRT/core/ProbeFormBridge.cpp
- SKIRT/core/ProbeFormBridge.hpp
- SKIRT/core/SecondaryDustLuminosityProbe.cpp
- SKIRT/core/SecondaryDustLuminosityProbe.hpp
- SKIRT/core/SimulationItemRegistry.cpp
The new `SecondaryDustLuminosityProbe` class allows probing the secondary dust luminosity as a function of wavelength, in combination with any of the available probe forms. For example, one can obtain the dust luminosity spectrum for each cell in the simulation's spatial grid, or construct noise-free images of the transparent dust surface brightness (i.e. ignoring the effects of scattering or absorption on the secondary radiation).
**Motivation**
This probe was suggested by user Niklas Moszczynski.
**Tests**
A functional test was added.
> Add probe for dust luminosity spectrum (with probe form)

- SKIRT/core/AllSkyInstrument.cpp
- SKIRT/core/AllSkyProjectionForm.cpp
- SKIRT/core/AxAngularDistribution.cpp
- SKIRT/core/BroadBand.cpp
- SKIRT/core/ComptonPhaseFunction.cpp
- SKIRT/core/ConvergenceInfoProbe.cpp
- SKIRT/core/CubicalBackgroundSource.cpp
- SKIRT/core/DipolePhaseFunction.cpp
- SKIRT/core/DistantInstrument.cpp
- SKIRT/core/DustMix.cpp
- SKIRT/core/DustSecondarySource.cpp
- SKIRT/core/FilePolarizedPointSource.cpp
- SKIRT/core/FilePolarizedPointSource.hpp
- SKIRT/core/HEALPixSkyInstrument.cpp
- SKIRT/core/LyaUtils.cpp
- SKIRT/core/ParallelProjectionForm.cpp
- SKIRT/core/PerspectiveInstrument.cpp
- SKIRT/core/Random.cpp
- SKIRT/core/SimulationItemRegistry.cpp
- SKIRT/core/SineSquarePolarizationProfile.cpp
- SKIRT/core/SineSquarePolarizationProfile.hpp
- SKIRT/core/SphericalBackgroundSource.cpp
- SKIRT/core/StellarSurfaceSource.cpp
- SKIRT/core/StoredTable.hpp
- SKIRT/utils/Direction.cpp
- SKIRT/utils/Direction.hpp
- SKIRT/utils/PathSegmentGenerator.hpp
- SKIRT/utils/StokesVector.cpp
- SKIRT/utils/StokesVector.hpp
- SKIRT/utils/Vec.hpp
This pull request adds the `FilePolarizedPointSource` class, representing a primary source limited to a single point in space and emitting polarized radiation with an axi-symmetric angular dependence. The Stokes vector components of the emitted radiation, as a function of wavelength and inclination angle cosine, are loaded from a user-provided file. The bolometric output is characterized by a `LuminosityNormalization` object configured in the ski file. The class furthermore offers user-configured properties to specify the position of the point source, the orientation of the symmetry axis of the angular dependence, and a "bulk" velocity.
**Motivation**
This functionality was requested by the IXPE team in Rome through @BertVdM for use in AGN models.
**Secondary changes**
The …
> Add FilePolarizedPointSource, using user-tabulated emission properties

- SKIRT/core/FilePolarizedPointSource.hpp
This update fixes an issue that blocked the use of `SpecificLuminosityNormalization` and `BandLuminosityNormalization` to normalize the luminosity of a `FilePolarizedPointSource`.
> Allow normalizing a FilePolarizedPointSource with specific luminosity

- CMakeLists.txt
- SKIRT/core/ClumpyGeometryDecorator.cpp
- SKIRT/core/FilePolarizedPointSource.hpp
This pull request fixes a few minor issues:
- The `ClumpyGeometryDecorator` now allows the fraction of the mass locked up in clumps to be 1 (previously, this would not work if the _cutoffClumps_ option was turned on).
- Build-time deprecation warnings issued by recent versions of `CMake` are now avoided.
- The "duplicate libraries" warning issued by some recent linkers (e.g. by Apple clang 15 on macOS) is now avoided when using `CMake` version **3.29.2** or higher (so you may need to upgrade CMake to get rid of this warning).
> Allow mass fraction of 1 in clumpy decorator; avoid some CMake warnings

- SKIRT/core/TabulatedBand.cpp
The `FileBand` and `ListBand` classes now issue a fatal error during setup if the user-defined band has an empty wavelength range, or if the wavelengths are not listed in increasing or decreasing order.
**Motivation**
Before this update, these classes accepted such invalid definitions but would then misbehave (such as generating NaN values).
**Context**
Reported by @BertVdM.
> Properly flag custom wavelength band with empty range

- SKIRT/core/DistantInstrument.cpp
- SKIRT/core/FITSInOut.cpp
- SKIRT/core/FITSInOut.hpp
- SKIRT/core/FluxRecorder.cpp
- SKIRT/core/FluxRecorder.hpp
With this update, parallel-projected instruments such as Frame and SED instruments add information on the observer sight line and model-observer distance to the output files, as a convenience to the user.
Specifically, FITS file headers now include additional keywords in the file header as in the following example:
CROTA1  =      4.500000000E+01 / Inclination angle, in deg                      
CROTA2  =      4.500000000E+01 / Azimuth angle, in deg                          
CROTA3  =      3.000000000E+01 / Roll angle, in deg                             
REDSHIFT=      2.000000000E+00 / Redshift (if zero, distances are equal)        
DISTLUMI=      1.607026089E+04 / Luminosity distance                            
DISTANGD=      1.785584544E+03 / Angular diameter distance …
> Add observer info to output of distant instruments

- SKIRT/core/CrystalEnstatiteGrainComposition.cpp
- SKIRT/core/CrystalForsteriteGrainComposition.cpp
- SKIRT/core/MinSilicateGrainComposition.cpp
A spelling error in the resource filename for the enthalpy data caused the following grain compositions to crash during setup when used with stochastic heating:
- `CrystalEnstatiteGrainComposition`
- `CrystalForsteriteGrainComposition`
- `MinSilicateGrainComposition`
This has now been fixed.
**Tests**
The functional tests for all grain compositions were updated to verify the proper resource is being used.
**Context**
This issue was reported by @andreagebek - thank you!
> Fix crash during setup when using some grain compositions with stochastic heating

- SKIRT/core/HirashitaLogNormalGrainSizeDistribution.cpp
- SKIRT/core/HirashitaLogNormalGrainSizeDistribution.hpp
- SKIRT/core/SimulationItemRegistry.cpp
We added a new class for dust grain size distributions from Hirashita (2015, https://ui.adsabs.harvard.edu/abs/2015MNRAS.447.2937H/abstract).
**Motivation**
The Hirashita (2015) dust grain size distribution is used for their popular two-size dust model. This grain size distributions has an additional prefactor (one over grain size to the fourth) in front of the "fiducial" log-normal dust grain size distribution in SKIRT.
**Tests**
We have used this grain size distribution to postprocess galaxies from the COLIBRE simulations.
**Guidelines**
-
**Context**
-
> Add Hirashita (2015) grain size distribution

- SKIRT/core/AdaptiveMeshSnapshot.cpp
- SKIRT/core/AdaptiveMeshSnapshot.hpp
- SKIRT/core/CellSnapshot.cpp
- SKIRT/core/CellSnapshot.hpp
- SKIRT/core/ParticleSnapshot.cpp
- SKIRT/core/ParticleSnapshot.hpp
- SKIRT/core/Snapshot.cpp
- SKIRT/core/Snapshot.hpp
- SKIRT/core/VoronoiMeshSnapshot.cpp
- SKIRT/core/VoronoiMeshSnapshot.hpp
- SKIRT/utils/EntityCollection.cpp
- SKIRT/utils/EntityCollection.hpp
**Motivation**
For an imported medium described by _smoothed particles_, when calculating the medium property values in each spatial grid cell during setup,  medium properties other than the medium density were taken from the particle nearest the sample location, rather than interpolating over all overlapping particles. Moreover, in rare cases, the code would use a particle close to the sample location but not the nearest particle.
With this new version, medium properties are sampled from an imported particle medium as follows:
- density is properly interpolated over all overlapping particles, as before.
- metallicity, temperature, bulk velocity, and magnetic field are now also properly interpolated over all overlapping particles using density-weighted averaging.
- any …
> Properly sample all properties from imported particle media

- .clang-format
- .github/workflows/check-formatting.yml
- SKIRT/core/AdaptiveMeshGeometry.cpp
- SKIRT/core/MultiParallel.cpp
- formatSourceCode.sh
**Motivation**
It has become hard to find and install `clang-format` version 9. However, the previous attempt in pull request #227 for updating the `clang-format` version was flawed. Please disregard any information in that pull request.
With this pull-request the SKIRT repository is updated to use `clang-format` version 18.1. This is the most recent version that can be easily installed on Ubuntu 24.04 and with some effort on macOS as well.
Specifically:
- The `formatSourceCode.sh` shell script and the GitHub format checking workflow now use `clang-format` version 18.1.
- The `formatSourceCode.sh` shell script now performs the formatting on multiple cores in parallel. 
- The Github format checking workflow now fails in case clang-format fails (e.g. because of an …
> Update format checking to clang-format version 18

- .clang-format
- SKIRT/core/AxPowerLawRedistributeGeometryDecorator.hpp
- SKIRT/core/DistantInstrument.hpp
- SKIRT/core/MonteCarloSimulation.cpp
- SKIRT/core/OligoWavelengthDistribution.hpp
- SKIRT/core/OligoWavelengthGrid.hpp
- SKIRT/core/SphePowerLawRedistributeGeometryDecorator.hpp
- SKIRT/core/SpheroidalGraphiteGrainComposition.hpp
- SKIRT/core/SpheroidalSilicateGrainComposition.hpp
- SKIRT/core/TetraMeshSpatialGrid.cpp
- SKIRT/utils/PhotonPacket.hpp
- SKIRT/utils/SpatialGridPath.hpp
- SMILE/fundamentals/System.cpp
- SMILE/fundamentals/System.hpp
- SMILE/shapes/ConvexPolygon.hpp
- SMILE/shapes/ShapeCanvas.cpp
This update tells clang-format to:
- always put an empty line before an access modifier
- remove empty lines at the start of a {} block
**Motivation**
Use the new features of clang-format version 18 to further clean up the code.
> Adjust source code formatting of empty lines

- SKIRT/core/AdaptiveMeshSource.hpp
- SKIRT/core/CellSource.hpp
- SKIRT/core/ImportedSource.cpp
- SKIRT/core/ImportedSource.hpp
- SKIRT/core/ParticleSnapshot.cpp
- SKIRT/core/ParticleSource.hpp
- SKIRT/core/Snapshot.cpp
- SKIRT/core/Snapshot.hpp
- SKIRT/core/VoronoiMeshSource.hpp
The `Snapshot` class now supports importing a bias column. This feature is utilized by the `ImportedSource` class to adjust photon counts across its entities, enabling users to prioritize photon launches from specific entities. However this bias may be used by any `Snapshot` in the future.
**Motivation**
Regions with low signal-to-noise ratios are challenging to improve without significantly increasing the number of photons launched. This update provides users with the ability to bias photon counts, allowing them to, for instance, assign higher biases to particles in certain regions. This results in more photons being launched from these regions, improving signal-to-noise.
**Tests**
All existing tests passed, and new tests were added to validate the bias functionality. …
> Add bias to `Snapshot` and Use in `ImportedSource`

- SKIRT/core/ImportedSourceLuminosityProbe.cpp
Precompute luminosities for all entities in `ImportedSourceLuminosityProbe` to speed up projection when `convolve=true`.
**Motivation**
The `ImportedSourceLuminosityProbe` is quite slow because it had to convolve the SED with the transmission curve for each entity, repeating this process for each pixel and recalculating the same quantity multiple times. The probe now precomputes this integral for each band and entity and stores it, allowing a fast look-up later. Although it may now compute quantities that are not used, the speed-up is still several 100 times faster for some simulations.
**Tests**
This implementation was validated by comparing projected images with the previous implementation to ensure identical results. Existing test cases already cover this functionality, …
> precalculate luminosities in `ImportedSourceLuminosityProbe`

- SKIRT/core/Cylinder3DSpatialGrid.hpp
- SKIRT/core/CylindricalCellSnapshot.cpp
- SKIRT/core/CylindricalCellSnapshot.hpp
- SKIRT/core/CylindricalCellSource.hpp
- SKIRT/core/SimulationItemRegistry.cpp
- SKIRT/core/Sphere1DSpatialGrid.cpp
- SKIRT/core/Sphere2DSpatialGrid.cpp
- SKIRT/core/Sphere3DSpatialGrid.cpp
- SKIRT/core/SphereSpatialGrid.hpp
- SKIRT/core/SphericalCellGeometry.cpp
- SKIRT/core/SphericalCellGeometry.hpp
- SKIRT/core/SphericalCellMedium.cpp
- SKIRT/core/SphericalCellMedium.hpp
- SKIRT/core/SphericalCellSnapshot.cpp
- SKIRT/core/SphericalCellSnapshot.hpp
- SKIRT/core/SphericalCellSource.cpp
- SKIRT/core/SphericalCellSource.hpp
- SKIRT/core/SymCosMesh.cpp
- SKIRT/core/SymCosMesh.hpp
- SKIRT/utils/Cubic.hpp
- SKIRT/utils/CylCell.cpp
- SKIRT/utils/CylCell.hpp
- SKIRT/utils/CylindricalCell.cpp
- SKIRT/utils/CylindricalCell.hpp
- SKIRT/utils/NR.hpp
- SKIRT/utils/SphericalCell.cpp
- SKIRT/utils/SphericalCell.hpp
This update adds the capability to import 1D, 2D, or 3D snapshots defined in spherical coordinates through the `SphericalSnapshot` class and the related import classes for sources and media. The functionality is very similar to what has been offered by the `CylindricalSnapshot` and related classes in a previous update.
The update also adds the `SymCosMesh` class, which can be used with the Sphere2DSpatialGrid and Sphere3DSpatialGrid classes to define a polar grid that has equal-volume bins.
**Motivation**
This update rounds up the effort to fully support non-Cartesian coordinates for both import and photon shooting.
**Tests**
New functional tests were added for the new classes; the existing tests did not change.
> Add import capability in spherical coordinates

- SKIRT/fitsio/putcol.c
- SMILE/fundamentals/Basics.hpp
- downloadResources.sh
The recent GCC version 15.1 introduced some incompatible changes that caused compilation to fail.
- the `<cstdint>` header must now be included explicitly (as opposed to implicitly through another header)
- `nullptr` is now a keyword also in plain C and thus can no longer be used as an variable name
The SKIRT code has been adapted to comply with these changes.
**Context**
This problem was reported in issue #250.
> Fix compiler errors for GCC 15.1
